-- Supabase SQL: create promo_codes table + useful indexes + trigger

create table if not exists public.promo_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_type text not null check (discount_type in ('fixed', 'percent')),
  discount_value numeric(10,2) not null check (discount_value > 0),
  min_subtotal numeric(10,2) not null default 0 check (min_subtotal >= 0),
  stripe_promotion_code_id text,
  is_active boolean not null default true,
  starts_at timestamptz,
  ends_at timestamptz,
  max_uses integer,
  used_count integer not null default 0 check (used_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint promo_codes_date_window_check check (
    starts_at is null or ends_at is null or starts_at <= ends_at
  ),
  constraint promo_codes_max_uses_check check (
    max_uses is null or max_uses >= 1
  ),
  constraint promo_codes_used_count_check check (
    max_uses is null or used_count <= max_uses
  )
);

create index if not exists promo_codes_code_idx on public.promo_codes (code);
create index if not exists promo_codes_active_idx on public.promo_codes (is_active);

create or replace function public.promo_codes_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists promo_codes_set_updated_at on public.promo_codes;
create trigger promo_codes_set_updated_at
before update on public.promo_codes
for each row
execute function public.promo_codes_set_updated_at();

-- Optional seed
insert into public.promo_codes (
  code,
  discount_type,
  discount_value,
  min_subtotal,
  is_active
)
values (
  'NOMADE10',
  'fixed',
  10,
  0,
  true
)
on conflict (code) do nothing;
