-- Supabase SQL: create collections and link categories to collections

create table if not exists public.collections (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  created_at timestamptz not null default now()
);

alter table if exists public.categories
  add column if not exists collection_id bigint references public.collections(id) on delete restrict;

create index if not exists categories_collection_id_idx
  on public.categories (collection_id);

insert into public.collections (name, slug, description)
values
  ('Sacs', 'sacs', 'Collection principale de sacs et maroquinerie nomade.'),
  ('Accessoires', 'accessoires', 'Petits objets et accessoires du quotidien.'),
  ('Autres', 'autres', 'Pieces hors collection principale.')
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description;

update public.categories
set collection_id = c.id
from public.collections c
where public.categories.collection_id is null
  and c.slug = case
    when lower(public.categories.slug) in ('cuir', 'minimal', 'bandouliere', 'aventure', 'route', 'voyage', 'sacs') then 'sacs'
    when lower(public.categories.slug) in ('accessoires', 'portefeuilles', 'portefeuille', 'montres', 'montre', 'trousses', 'trousse') then 'accessoires'
    else 'autres'
  end;

alter table if exists public.categories
  alter column collection_id set not null;